/**
 * Project data for the CIFO Violeta Showcase.
 * Used by modal.js to populate the quick-view modal with full project details.
 */

export const projectsData = [
    {
        id: 'proj-001',
        title: 'MedTrack — Gestión de Citas Médicas',
        slug: 'medtrack-gestion-citas',
        descriptionLong: 'MedTrack es una plataforma integral de gestión sanitaria que permite a pacientes y profesionales médicos coordinar citas de manera eficiente. Incluye un calendario interactivo con drag & drop, sistema de notificaciones push, historial clínico del paciente y un dashboard analítico para el centro médico. Desarrollado con Laravel y Vue.js, implementa autenticación multifactor y cumple con la normativa RGPD para datos sensibles.',
        imagesGallery: [
            'https://picsum.photos/seed/medtrack1/1200/800',
            'https://picsum.photos/seed/medtrack2/1200/800',
            'https://picsum.photos/seed/medtrack3/1200/800',
        ],
        student: 'Marina López García',
        course: 'Desarrollo de Aplicaciones Web (DAW)',
        courseCode: 'DAW',
        professor: 'Carlos Martínez',
        year: '2025',
        technologies: ['Laravel', 'Vue.js', 'MySQL', 'Tailwind CSS', 'WebSockets'],
        tags: ['Salud', 'Full Stack', 'API REST'],
    },
    {
        id: 'proj-002',
        title: 'EcoRuta — Rutas Sostenibles BCN',
        slug: 'ecoruta-rutas-sostenibles',
        descriptionLong: 'EcoRuta transforma la movilidad urbana en Barcelona mediante una aplicación que calcula rutas optimizadas para bicicleta, patinete y transporte público. Integra un sistema de gamificación donde los usuarios acumulan puntos verdes canjeables, un calculador de huella de carbono comparativa y mapas de calor de calidad del aire. El backend procesa datos de la API de TMB y Bicing en tiempo real.',
        imagesGallery: [
            'https://picsum.photos/seed/ecoruta1/1200/800',
            'https://picsum.photos/seed/ecoruta2/1200/800',
            'https://picsum.photos/seed/ecoruta3/1200/800',
        ],
        student: 'Adrià Puig Fernández',
        course: 'Desarrollo de Aplicaciones Multiplataforma (DAM)',
        courseCode: 'DAM',
        professor: 'Laura Sánchez',
        year: '2025',
        technologies: ['Kotlin', 'Jetpack Compose', 'Firebase', 'Google Maps API', 'Room DB'],
        tags: ['Movilidad', 'Sostenibilidad', 'Mobile'],
    },
    {
        id: 'proj-003',
        title: 'ShieldNet — Monitor de Red Empresarial',
        slug: 'shieldnet-monitor-red',
        descriptionLong: 'ShieldNet proporciona visibilidad completa sobre la infraestructura de red de una PYME. Monitoriza en tiempo real el tráfico de red, detecta patrones anómalos mediante reglas configurables, genera alertas por email y Telegram, y ofrece un dashboard con métricas históricas. Implementa SNMP, syslog y análisis de paquetes con una interfaz web accesible para administradores sin conocimientos avanzados de ciberseguridad.',
        imagesGallery: [
            'https://picsum.photos/seed/shieldnet1/1200/800',
            'https://picsum.photos/seed/shieldnet2/1200/800',
            'https://picsum.photos/seed/shieldnet3/1200/800',
        ],
        student: 'Fatima El Amrani',
        course: 'Administración de Sistemas Informáticos en Red (ASIR)',
        courseCode: 'ASIR',
        professor: 'Jordi Vila',
        year: '2024',
        technologies: ['Python', 'Grafana', 'Prometheus', 'Docker', 'PostgreSQL'],
        tags: ['Seguridad', 'Redes', 'DevOps'],
    },
    {
        id: 'proj-004',
        title: 'PixelCraft — Editor Gráfico Online',
        slug: 'pixelcraft-editor-grafico',
        descriptionLong: 'PixelCraft es un editor gráfico accesible desde el navegador que permite manipular imágenes con un sistema de capas, aplicar filtros prediseñados y personalizados, recortar, rotar y ajustar parámetros como brillo, contraste y saturación. Utiliza la Canvas API de HTML5 para el renderizado en tiempo real y Web Workers para operaciones pesadas sin bloquear la interfaz. Soporta exportación en PNG, JPEG, WebP y SVG.',
        imagesGallery: [
            'https://picsum.photos/seed/pixelcraft1/1200/800',
            'https://picsum.photos/seed/pixelcraft2/1200/800',
            'https://picsum.photos/seed/pixelcraft3/1200/800',
        ],
        student: 'Pol Ramírez Costa',
        course: 'Desarrollo de Aplicaciones Web (DAW)',
        courseCode: 'DAW',
        professor: 'Carlos Martínez',
        year: '2024',
        technologies: ['JavaScript', 'Canvas API', 'Web Workers', 'IndexedDB', 'CSS Grid'],
        tags: ['Creatividad', 'Frontend', 'Herramientas'],
    },
    {
        id: 'proj-005',
        title: 'TechRepair — Gestión de Incidencias IT',
        slug: 'techrepair-gestion-incidencias',
        descriptionLong: 'TechRepair digitaliza el flujo completo de incidencias técnicas de un centro educativo. Los usuarios reportan problemas desde un formulario intuitivo, el sistema asigna prioridad automáticamente según categoría y urgencia, y los técnicos gestionan los tickets desde un panel Kanban. Incluye base de conocimiento con soluciones frecuentes, métricas de tiempo de resolución y generación automática de informes mensuales en PDF.',
        imagesGallery: [
            'https://picsum.photos/seed/techrepair1/1200/800',
            'https://picsum.photos/seed/techrepair2/1200/800',
            'https://picsum.photos/seed/techrepair3/1200/800',
        ],
        student: 'Sergio Navarro Díaz',
        course: 'Sistemas Microinformáticos y Redes (SMX)',
        courseCode: 'SMX',
        professor: 'Ana Ruiz',
        year: '2025',
        technologies: ['PHP', 'MySQL', 'Bootstrap', 'jQuery', 'FPDF'],
        tags: ['Soporte', 'Gestión', 'Backend'],
    },
    {
        id: 'proj-006',
        title: 'FoodMap — Mapa Gastronómico Colaborativo',
        slug: 'foodmap-mapa-gastronomico',
        descriptionLong: 'FoodMap permite a los usuarios descubrir y compartir restaurantes, bares y mercados de Barcelona a través de un mapa interactivo con filtros por tipo de cocina, precio y valoración. Los usuarios pueden crear listas personalizadas, dejar reseñas con fotos y seguir a otros foodies. El algoritmo de recomendación analiza los gustos del usuario para sugerir nuevos establecimientos. Integra la API de Google Maps y un sistema de moderación de contenido.',
        imagesGallery: [
            'https://picsum.photos/seed/foodmap1/1200/800',
            'https://picsum.photos/seed/foodmap2/1200/800',
            'https://picsum.photos/seed/foodmap3/1200/800',
        ],
        student: 'Clara Moreno Ibáñez',
        course: 'Desarrollo de Aplicaciones Web (DAW)',
        courseCode: 'DAW',
        professor: 'Laura Sánchez',
        year: '2024',
        technologies: ['React', 'Node.js', 'MongoDB', 'Google Maps API', 'Cloudinary'],
        tags: ['Geolocalización', 'Social', 'Full Stack'],
    },
    {
        id: 'proj-007',
        title: 'CloudDesk — Escritorio Virtual Educativo',
        slug: 'clouddesk-escritorio-virtual',
        descriptionLong: 'CloudDesk despliega escritorios virtuales Linux y Windows accesibles desde cualquier navegador para las aulas del CIFO. Los profesores pueden crear plantillas de escritorio con software preconfigurado para cada curso, los alumnos acceden a su entorno personalizado desde cualquier equipo, y los administradores monitorizan el uso de recursos en tiempo real. Implementa virtualización con Proxmox, contenedores Docker para servicios auxiliares y Apache Guacamole como cliente web.',
        imagesGallery: [
            'https://picsum.photos/seed/clouddesk1/1200/800',
            'https://picsum.photos/seed/clouddesk2/1200/800',
            'https://picsum.photos/seed/clouddesk3/1200/800',
        ],
        student: 'Marc Oliveras Vidal',
        course: 'Administración de Sistemas Informáticos en Red (ASIR)',
        courseCode: 'ASIR',
        professor: 'Jordi Vila',
        year: '2025',
        technologies: ['Proxmox', 'Docker', 'Apache Guacamole', 'Ansible', 'Bash'],
        tags: ['Virtualización', 'Infraestructura', 'Educación'],
    },
    {
        id: 'proj-008',
        title: 'SoundWave — Plataforma de Podcasts',
        slug: 'soundwave-plataforma-podcasts',
        descriptionLong: 'SoundWave permite a creadores de contenido grabar, editar y publicar podcasts directamente desde el navegador. Incluye un editor de audio básico con corte y mezcla, transcripción automática mediante la Web Speech API, generación automática de feed RSS para distribución en Spotify y Apple Podcasts, y un panel de analytics con métricas de escucha. Los oyentes disfrutan de un reproductor web con cola de reproducción y suscripciones.',
        imagesGallery: [
            'https://picsum.photos/seed/soundwave1/1200/800',
            'https://picsum.photos/seed/soundwave2/1200/800',
            'https://picsum.photos/seed/soundwave3/1200/800',
        ],
        student: 'Noa Castells Prat',
        course: 'Desarrollo de Aplicaciones Multiplataforma (DAM)',
        courseCode: 'DAM',
        professor: 'Carlos Martínez',
        year: '2024',
        technologies: ['Flutter', 'Dart', 'Firebase', 'Web Audio API', 'FFmpeg'],
        tags: ['Audio', 'Multimedia', 'Multiplataforma'],
    },
    {
        id: 'proj-009',
        title: 'NetLab — Simulador de Topologías de Red',
        slug: 'netlab-simulador-redes',
        descriptionLong: 'NetLab es una herramienta educativa que permite a los alumnos de redes diseñar topologías arrastrando y conectando dispositivos virtuales (routers, switches, PCs, servidores) sobre un canvas interactivo. El simulador valida la configuración IP, simula el tráfico de paquetes visualmente y ejecuta tests automáticos para evaluar si la topología cumple los requisitos del ejercicio. Los profesores pueden crear y compartir prácticas con rúbricas de evaluación integradas.',
        imagesGallery: [
            'https://picsum.photos/seed/netlab1/1200/800',
            'https://picsum.photos/seed/netlab2/1200/800',
            'https://picsum.photos/seed/netlab3/1200/800',
        ],
        student: 'Javier Soto Blanco',
        course: 'Sistemas Microinformáticos y Redes (SMX)',
        courseCode: 'SMX',
        professor: 'Ana Ruiz',
        year: '2024',
        technologies: ['JavaScript', 'Canvas API', 'Node.js', 'Socket.io', 'SQLite'],
        tags: ['Educación', 'Simulación', 'Redes'],
    },
    {
        id: 'proj-010',
        title: 'GreenHouse — Monitorización IoT de Invernadero',
        slug: 'greenhouse-iot-invernadero',
        descriptionLong: 'GreenHouse conecta sensores de temperatura, humedad, luminosidad y pH del suelo a un microcontrolador ESP32 que transmite datos via MQTT a un servidor central. La aplicación web muestra dashboards en tiempo real con gráficas históricas, permite configurar umbrales de alerta y activa actuadores (riego, ventilación, iluminación LED) de forma automática o manual. Incluye una app companion en Android para monitorización remota y notificaciones push.',
        imagesGallery: [
            'https://picsum.photos/seed/greenhouse1/1200/800',
            'https://picsum.photos/seed/greenhouse2/1200/800',
            'https://picsum.photos/seed/greenhouse3/1200/800',
        ],
        student: 'Laia Ferrer Bosch',
        course: 'Desarrollo de Aplicaciones Multiplataforma (DAM)',
        courseCode: 'DAM',
        professor: 'Laura Sánchez',
        year: '2025',
        technologies: ['ESP32', 'MQTT', 'Node.js', 'InfluxDB', 'Grafana', 'Kotlin'],
        tags: ['IoT', 'Hardware', 'Automatización'],
    },
];
